### ISSUE TITLE
Struggling to make workspaces.sh working

### ISSUE THREAD

**Issue by antieksi** [NotMugil/niri-dots#5]
Hi. I'm starting to use niri as a daily driver myself, and even though I mostly write all the configs myself, I took a workspaces script from this repository. Sadly, whenever I run waybar, the custom workspaces module doesn't poll after changing different workspaces. Though it does work if I use interval polling. It's a little hard for me to read bash-scripts, so I would appreciate if you helped out with it. Thanks!

**Comment by NotMugil** [comment]
I see what you mean. It sounds like the script isn't making waybar update automatically when you switch workspaces. The thing is that, the script `exec_and_signal.sh` works by sending signal to waybar whenever there is a workspace change to keep it in sync. 

In the keybindings of my niri configuration (config.kdl), I've set it up so that whenever I change focus to a different workspace, it triggers the exec_and_signal.sh script. However, it seems there are still some issues with this setup.

For further details you can check out the discussion thread on Niri Github [here](https://github.com/YaLTeR/niri/discussions/356).

**Comment by antieksi** [comment]
I guess I simply didn't notice this script the first time. Thanks for pointing out!
